#version 450

#extension GL_GOOGLE_include_directive : enable
#extension GL_KHR_shader_subgroup_arithmetic: enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64: enable
#extension GL_EXT_shader_atomic_int64: enable

#include "statistics.glsl"

layout(constant_id = 0) const uint WORKGROUP_SIZE = 128;
layout(local_size_x_id = 0) in;

layout(std430, binding = 0) readonly buffer FirstEdges { uint first_edges[]; };
layout(std430, binding = 1) readonly buffer Targets { uint targets[]; };
layout(std430, binding = 2) readonly buffer Weight { uint weight[]; };
layout(std430, binding = 3) coherent buffer Dist { uint dist[]; };
// Results buffer: [0] = best_distance (dist[dst_node])
layout(std430, binding = 4) coherent buffer Results { uint results[]; };
// Changed flag: set to 1 if any distance was updated
layout(std430, binding = 5) coherent buffer Changed { uint changed; };
// Statistics counters
layout(std430, binding = 6) coherent buffer StatisticsCounters { uint64_t statistics_counters[]; };

layout(push_constant) uniform PushConsts {
    uint src_node;
    uint dst_node;
    uint n;
} pc;

#define INF_WEIGHT 0x3fffffff

void main() {
    uint u = gl_GlobalInvocationID.x;
    if (u >= pc.n) return;

    if (u == pc.dst_node) {
        atomicMin(results[0], dist[u]);
    }

    uint du = dist[u];
    if (du < INF_WEIGHT) {
        uint local_changed = 0;
        for (uint eid = first_edges[u]; eid < first_edges[u+1]; ++eid) {
            statisticsCount(STAT_BELLMANFORD_EDGES_RELAXED);
            
            uint v = targets[eid];
            uint w = weight[eid];
            uint alt = du + w;
            uint prev = atomicMin(dist[v], alt);
            if (alt < prev) {
                statisticsCount(STAT_BELLMANFORD_EDGES_IMPROVED);
                local_changed++;
            }
        }
        uint all_changed = subgroupMax(local_changed);
        if (subgroupElect() && all_changed > 0) {
            atomicMax(changed, 1);
        }
    }
}
