#ifndef NEARFAR_CONSTANTS_GLSL
#define NEARFAR_CONSTANTS_GLSL

#define COUNTER_NUM_NEAR 0
#define COUNTER_NUM_NEAR_NEXT 1
#define COUNTER_NUM_FAR 2
#define COUNTER_NUM_FAR_NEXT 3

#define RESULT_BEST_DISTANCE 0
#define RESULT_NUM_NEAR 1
#define RESULT_NUM_FAR 2

#endif
